<!DOCTYPE html><html lang="en" ><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><meta name="day-prompt" content="days ago"><meta name="hour-prompt" content="hours ago"><meta name="minute-prompt" content="minutes ago"><meta name="justnow-prompt" content="just now"><meta name="generator" content="Jekyll v4.2.2" /><meta property="og:title" content="자바 스터디 09 - 예외 처리" /><meta name="author" content="yeoji21" /><meta property="og:locale" content="en" /><meta name="description" content="어서와" /><meta property="og:description" content="어서와" /><link rel="canonical" href="https://yeoji21.github.io/posts/javastudy09/" /><meta property="og:url" content="https://yeoji21.github.io/posts/javastudy09/" /><meta property="og:site_name" content="yeoji21" /><meta property="og:type" content="article" /><meta property="article:published_time" content="2021-08-21T00:00:00+09:00" /><meta name="twitter:card" content="summary" /><meta property="twitter:title" content="자바 스터디 09 - 예외 처리" /><meta name="twitter:site" content="@twitter_username" /><meta name="twitter:creator" content="@yeoji21" /><meta name="google-site-verification" content="google_meta_tag_verification" /> <script type="application/ld+json"> {"@context":"https://schema.org","@type":"BlogPosting","author":{"@type":"Person","name":"yeoji21"},"dateModified":"2022-01-11T00:08:15+09:00","datePublished":"2021-08-21T00:00:00+09:00","description":"어서와","headline":"자바 스터디 09 - 예외 처리","mainEntityOfPage":{"@type":"WebPage","@id":"https://yeoji21.github.io/posts/javastudy09/"},"url":"https://yeoji21.github.io/posts/javastudy09/"}</script><title>자바 스터디 09 - 예외 처리 | yeoji21</title><link rel="apple-touch-icon" sizes="180x180" href="/assets/img/favicons/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicons/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicons/favicon-16x16.png"><link rel="manifest" href="/assets/img/favicons/site.webmanifest"><link rel="shortcut icon" href="/assets/img/favicons/favicon.ico"><meta name="apple-mobile-web-app-title" content="yeoji21"><meta name="application-name" content="yeoji21"><meta name="msapplication-TileColor" content="#da532c"><meta name="msapplication-config" content="/assets/img/favicons/browserconfig.xml"><meta name="theme-color" content="#ffffff"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous"><link rel="dns-prefetch" href="https://fonts.gstatic.com"><link rel="preconnect" href="https://www.google-analytics.com" crossorigin="use-credentials"><link rel="dns-prefetch" href="https://www.google-analytics.com"><link rel="preconnect" href="https://www.googletagmanager.com" crossorigin="anonymous"><link rel="dns-prefetch" href="https://www.googletagmanager.com"><link rel="preconnect" href="https://cdn.jsdelivr.net"><link rel="dns-prefetch" href="https://cdn.jsdelivr.net"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.11.2/css/all.min.css"><link rel="stylesheet" href="/assets/css/style.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/afeld/bootstrap-toc@1.0.1/dist/bootstrap-toc.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/magnific-popup@1.1.0/dist/magnific-popup.min.css"> <script src="https://cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js"></script><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@500&display=swap" rel="stylesheet"><body data-spy="scroll" data-target="#toc"><div id="sidebar" class="d-flex flex-column align-items-end" lang="en"><div class="profile-wrapper text-center"><div id="avatar"> <a href="/" alt="avatar" class="mx-auto"> <img src="/assets/img/profile/img1.JPG" alt="avatar" onerror="this.style.display='none'"> </a></div><div class="site-title mt-3"> <a href="/">yeoji21</a></div><div class="site-subtitle font-italic">Don't look back in anger</div></div><ul class="w-100"><li class="nav-item"> <a href="/" class="nav-link"> <i class="fa-fw fas fa-home ml-xl-3 mr-xl-3 unloaded"></i> <span>HOME</span> </a><li class="nav-item"> <a href="/categories/" class="nav-link"> <i class="fa-fw fas fa-stream ml-xl-3 mr-xl-3 unloaded"></i> <span>CATEGORIES</span> </a><li class="nav-item"> <a href="/tags/" class="nav-link"> <i class="fa-fw fas fa-tags ml-xl-3 mr-xl-3 unloaded"></i> <span>TAGS</span> </a><li class="nav-item"> <a href="/archives/" class="nav-link"> <i class="fa-fw fas fa-archive ml-xl-3 mr-xl-3 unloaded"></i> <span>ARCHIVES</span> </a></ul><div class="sidebar-bottom mt-auto d-flex flex-wrap justify-content-center"> <a href="https://github.com/yeoji21" aria-label="github" class="order-3" target="_blank" rel="noopener"> <i class="fab fa-github-alt"></i> </a> <a href="https://twitter.com/twitter_username" aria-label="twitter" class="order-4" target="_blank" rel="noopener"> <i class="fab fa-twitter"></i> </a> <a href=" javascript:location.href = 'mailto:' + ['yeozone0508','gmail.com'].join('@')" aria-label="email" class="order-5" > <i class="fas fa-envelope"></i> </a> <a href="/feed.xml" aria-label="rss" class="order-6" > <i class="fas fa-rss"></i> </a> <span class="icon-border order-2"></span> <span id="mode-toggle-wrapper" class="order-1"> <i class="mode-toggle fas fa-adjust"></i> <script type="text/javascript"> class ModeToggle { static get MODE_KEY() { return "mode"; } static get DARK_MODE() { return "dark"; } static get LIGHT_MODE() { return "light"; } constructor() { if (this.hasMode) { if (this.isDarkMode) { if (!this.isSysDarkPrefer) { this.setDark(); } } else { if (this.isSysDarkPrefer) { this.setLight(); } } } var self = this; /* always follow the system prefers */ this.sysDarkPrefers.addListener(function() { if (self.hasMode) { if (self.isDarkMode) { if (!self.isSysDarkPrefer) { self.setDark(); } } else { if (self.isSysDarkPrefer) { self.setLight(); } } self.clearMode(); } self.updateMermaid(); }); } /* constructor() */ setDark() { $('html').attr(ModeToggle.MODE_KEY, ModeToggle.DARK_MODE); sessionStorage.setItem(ModeToggle.MODE_KEY, ModeToggle.DARK_MODE); } setLight() { $('html').attr(ModeToggle.MODE_KEY, ModeToggle.LIGHT_MODE); sessionStorage.setItem(ModeToggle.MODE_KEY, ModeToggle.LIGHT_MODE); } clearMode() { $('html').removeAttr(ModeToggle.MODE_KEY); sessionStorage.removeItem(ModeToggle.MODE_KEY); } get sysDarkPrefers() { return window.matchMedia("(prefers-color-scheme: dark)"); } get isSysDarkPrefer() { return this.sysDarkPrefers.matches; } get isDarkMode() { return this.mode == ModeToggle.DARK_MODE; } get isLightMode() { return this.mode == ModeToggle.LIGHT_MODE; } get hasMode() { return this.mode != null; } get mode() { return sessionStorage.getItem(ModeToggle.MODE_KEY); } /* get the current mode on screen */ get modeStatus() { if (this.isDarkMode || (!this.hasMode && this.isSysDarkPrefer) ) { return ModeToggle.DARK_MODE; } else { return ModeToggle.LIGHT_MODE; } } updateMermaid() { if (typeof mermaid !== "undefined") { let expectedTheme = (this.modeStatus === ModeToggle.DARK_MODE? "dark" : "default"); let config = { theme: expectedTheme }; /* re-render the SVG › <https://github.com/mermaid-js/mermaid/issues/311#issuecomment-332557344> */ $(".mermaid").each(function() { let svgCode = $(this).prev().children().html(); $(this).removeAttr("data-processed"); $(this).html(svgCode); }); mermaid.initialize(config); mermaid.init(undefined, ".mermaid"); } } flipMode() { if (this.hasMode) { if (this.isSysDarkPrefer) { if (this.isLightMode) { this.clearMode(); } else { this.setLight(); } } else { if (this.isDarkMode) { this.clearMode(); } else { this.setDark(); } } } else { if (this.isSysDarkPrefer) { this.setLight(); } else { this.setDark(); } } this.updateMermaid(); } /* flipMode() */ } /* ModeToggle */ let toggle = new ModeToggle(); $(".mode-toggle").click(function() { toggle.flipMode(); }); </script> </span></div></div><div id="topbar-wrapper" class="row justify-content-center topbar-down"><div id="topbar" class="col-11 d-flex h-100 align-items-center justify-content-between"> <span id="breadcrumb"> <span> <a href="/"> Home </a> </span> <span>자바 스터디 09 - 예외 처리</span> </span> <i id="sidebar-trigger" class="fas fa-bars fa-fw"></i><div id="topbar-title"> Post</div><i id="search-trigger" class="fas fa-search fa-fw"></i> <span id="search-wrapper" class="align-items-center"> <i class="fas fa-search fa-fw"></i> <input class="form-control" id="search-input" type="search" aria-label="search" autocomplete="off" placeholder="Search..."> <i class="fa fa-times-circle fa-fw" id="search-cleaner"></i> </span> <span id="search-cancel" >Cancel</span></div></div><div id="main-wrapper"><div id="main"><div class="row"><div id="post-wrapper" class="col-12 col-lg-11 col-xl-8"><div class="post pl-1 pr-1 pl-sm-2 pr-sm-2 pl-md-4 pr-md-4"><h1 data-toc-skip>자바 스터디 09 - 예외 처리</h1><div class="post-meta text-muted d-flex flex-column"><div> <span class="semi-bold"> yeoji21 </span> on <span class="timeago " data-toggle="tooltip" data-placement="bottom" title="Sat, Aug 21, 2021, 12:00 AM +0900" >Aug 21, 2021<i class="unloaded">2021-08-21T00:00:00+09:00</i> </span></div><div> <span> Updated <span class="timeago lastmod" data-toggle="tooltip" data-placement="bottom" title="Tue, Jan 11, 2022, 12:08 AM +0900" >Jan 11<i class="unloaded">2022-01-11T00:08:15+09:00</i> </span> </span> <span class="readtime" data-toggle="tooltip" data-placement="bottom" title="6355 words">35 min read</span></div></div><div class="post-content"><p><img data-proofer-ignore data-src="https://media.vlpt.us/images/inhalin/post/b48b4cd3-619b-4bf4-939c-d3546dd2ec01/whiteship.png" /></p><h2 id="들어가면서">들어가면서</h2><p>백기선님이 진행하신 자바 스터디 강의와 스터디에 참여하신 분들의 자료를 참고하여 작성한 글입니다.<br /> 강의 영상 링크 : <a href="https://www.youtube.com/watch?v=ULKUslGh8cg&amp;list=PLfI752FpVCS96fSsQe2E3HzYTgdmbz6LU&amp;index=18">[자바 라이브 스터디] 2020/1/16, 9주차 예외 </a><br /> 강의 깃허브 링크 : <a href="https://github.com/whiteship/live-study/issues/9">9주차 과제: 예외 처리</a></p><h2 id="목차">목차</h2><ul><li>자바에서 예외 처리 방법 (try, catch, throw, throws, finally)<li>자바가 제공하는 예외 계층 구조<li>Exception과 Error의 차이는?<li>RuntimeException과 RE가 아닌 것의 차이는?<li>커스텀한 예외 만드는 방법</ul><h3 id="exception과-error의-차이는"><strong>Exception과 Error의 차이는?</strong></h3><p>자바에서 에러는 크게 <code class="language-plaintext highlighter-rouge">컴파일 에러</code>와 <code class="language-plaintext highlighter-rouge">런타임 에러</code>로 나뉜다.<br /> 컴파일 에러는 말 그대로 컴파일 시에 발생하는 에러를 말하고, 런타임 에러는 런타임 시에 발생하는 에러를 말한다.</p><p><strong>컴파일 에러</strong>는 자바 컴파일러가 문법 검사를 통해 오류를 미리 잡아준다. IDE에서 코드를 작성할 때 빨간줄이 뜨면서 컴파일 에러를 경고해주는 것을 본 적이 있을 것이다.</p><p>그러나 컴파일이 문제없이 되더라도 실행 과정에서 <strong>런타임 에러</strong>가 발생할 수 있다. 런타임 에러는 프로그램 실행 중에 일어날 수 있는 모든 경우의 수를 고려하여 대비할 필요가 있다.</p><p>자바에서는 런타임 에러를 예외(Exception)와 에러(Error)로 구분하고 있다. 클래스 계층구조는 아래와 같다.</p><p><img data-proofer-ignore data-src="https://github.com/ByungJun25/study/raw/main/java/whiteship-study/9week/Throwable.png" width="600" /></p><p>출처 : <a href="https://github.com/ByungJun25/study/tree/main/java/whiteship-study/9week">https://github.com/ByungJun25/study/tree/main/java/whiteship-study/9week</a></p><p><code class="language-plaintext highlighter-rouge">Error</code>는 메모리 부족(OutOfMemoryError), 스택 오버플로우(StackOverFlowError)처럼 JVM이나 하드웨어 등 시스템 레벨 상의 문제로 인해 발생한다. 에러가 발생하면 프로그램은 무조건 비정상 종료되기 때문에 애초에 발생하지 않도록 해야 한다.</p><p><code class="language-plaintext highlighter-rouge">Exception</code>은 프로그램 상의 오류로 인해 발생하는 프로그램 오류이다. 발생하더라도 미리 적절한 코드를 작성하여 프로그램이 비정상적으로 종료되지 않도록 핸들링할 수 있으며 이를 예외 처리라고 한다.</p><h3 id="자바에서-예외-처리-방법-try-catch-throw-throws-finally"><strong>자바에서 예외 처리 방법 (try, catch, throw, throws, finally)</strong></h3><h4 id="try-catch-블럭">try-catch 블럭</h4><p>예외처리(Exception Handling)란, 프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생을 대비한 코드를 작성하는 것이며, 예외처리의 목적은 예외의 발생으로 인한 실행 중인 프로그램의 갑작스러운 비정상 종료를 막고, 실행상태를 유지하도록 하기 위함이다.</p><p>만약 발생한 예외를 처리하지 못하면, 처리되지 못한 예외(uncaught exception)는 JVM의 <code class="language-plaintext highlighter-rouge">예외 처리기(UncaughtExceptionHandler)</code>가 받아서 해당 예외가 담고있던 <code class="language-plaintext highlighter-rouge">Stack Trace</code>를 출력하면서 프로그램이 종료된다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
</pre><td class="rouge-code"><pre><span class="k">try</span><span class="o">{</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"try-catch 예제"</span><span class="o">);</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="mi">10</span> <span class="o">/</span> <span class="mi">0</span><span class="o">);</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"예외 발생 시 이 문장은 실행되지 않음"</span><span class="o">);</span>
<span class="o">}</span><span class="k">catch</span><span class="o">(</span><span class="nc">ArithmeticException</span> <span class="n">e</span><span class="o">){</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"정수형을  0으로 나누면 에러 발생"</span><span class="o">);</span>
<span class="o">}</span>
</pre></table></code></div></div><div lang="console" class="language-console highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
</pre><td class="rouge-code"><pre><span class="go">try-catch 예제
정수형을  0으로 나누면 에러 발생
</span></pre></table></code></div></div><p>위 코드는 정수를 0으로 나누기 때문에 <code class="language-plaintext highlighter-rouge">ArithmeticException</code>이 발생한다. try 블럭 내에서 예외가 발생하면, 즉시 try 블럭을 나와서 <code class="language-plaintext highlighter-rouge">ArithmeticException</code>을 처리할 수 있는 catch 블럭이 존재하는지 찾는다.</p><p>만약 적절한 catch 블럭을 찾았다면 catch 블럭 내 코드를 실행한 다음 try-catch문을 벗어난다. 따라서 위 코드는 예외가 발생했지만 적절한 예외처리를 통해 정상종료되었다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
</pre><td class="rouge-code"><pre><span class="k">try</span><span class="o">{</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"try-catch 예제"</span><span class="o">);</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="mi">10</span> <span class="o">/</span> <span class="mi">0</span><span class="o">);</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"예외 발생 시 이 문장은 실행되지 않음"</span><span class="o">);</span>
<span class="o">}</span><span class="k">catch</span><span class="o">(</span><span class="nc">NumberFormatException</span> <span class="n">e1</span><span class="o">){</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"NumberFormatException 발생"</span><span class="o">);</span>
<span class="o">}</span>
<span class="k">catch</span><span class="o">(</span><span class="nc">ArithmeticException</span> <span class="n">e2</span><span class="o">){</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"ArithmeticException 발생"</span><span class="o">);</span>
<span class="o">}</span>
<span class="k">catch</span><span class="o">(</span><span class="nc">Exception</span> <span class="n">e3</span><span class="o">){</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"Exception 발생"</span><span class="o">);</span>
<span class="o">}</span>
</pre></table></code></div></div><p>하나의 try 블럭에 대해 여러 종류의 예외를 처리할 수 있도록 여러 개의 catch 블럭을 사용할 수도 있다. 이 중에서 발생한 예외의 종류와 일치하는 단 하나의 catch 블럭만 수행된다.</p><blockquote><p>이 때 try 블럭에서 발생한 실제 예외와 catch 블럭의 예외를 instanceof 연산자를 통해 검사한다.</p></blockquote><p>이 때 주의해야할 것은 위에 있는 catch 블럭에서 걸리면 아래에 있는 catch 블럭은 호출되지 않는다는 점이다. 그렇기때문에 예를 들어 위에 블럭에 <code class="language-plaintext highlighter-rouge">RuntimeException</code>을 잡아놓고, 그 밑에 <code class="language-plaintext highlighter-rouge">IllegalArgumentException</code>을 잡아놨다면 잘못된 코드이다. 이런 경우가 발생하면 IDE에서 에러로 알려준다.</p><h4 id="멀티-catch-블럭">멀티 catch 블럭</h4><p>JDK 1.7부터 여러 catch 블럭에 대해 같은 처리를 할 때 <code class="language-plaintext highlighter-rouge">|</code>기호를 통해 하나의 catch 블럭으로 합칠 수 있게 되었다. 이를 멀티 catch 블럭이라 하며 합칠 수 있는 예외 클래스의 개수는 제한이 없다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
</pre><td class="rouge-code"><pre><span class="k">catch</span><span class="o">(</span><span class="nc">NumberFormatException</span> <span class="o">|</span> <span class="nc">ArithmeticException</span> <span class="n">e</span><span class="o">){</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"Exception 발생"</span><span class="o">);</span>
    <span class="n">e</span><span class="o">.</span><span class="na">printStackTrace</span><span class="o">():</span>
<span class="o">}</span>
</pre></table></code></div></div><p>하지만 이때 <code class="language-plaintext highlighter-rouge">|</code>로 연결된 두 예외 클래스가 조상과 자손 관계라면 컴파일 에러가 발생하므로 주의해야 한다.</p><h4 id="예외-발생시키기-throw">예외 발생시키기 throw</h4><p>키워드 <code class="language-plaintext highlighter-rouge">throw</code>를 사용해 고의로 예외를 발생시킬 수 있다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
</pre><td class="rouge-code"><pre><span class="k">try</span><span class="o">{</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nf">Exception</span><span class="o">(</span><span class="s">"고의로 만든 예외"</span><span class="o">);</span>
<span class="o">}</span>
<span class="k">catch</span><span class="o">(</span><span class="nc">Exception</span> <span class="n">e</span><span class="o">){</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"Exception 발생"</span><span class="o">);</span>
<span class="o">}</span>
</pre></table></code></div></div><p>이 것을 이용하여 예외를 잡아서(catch) 다른 예외를 던지는 <strong>예외 전환</strong>을 사용할 수도 있다. 호출한 쪽에서 예외를 받아서 처리할 때 좀 더 명확하게 인지할 수 있도록 돕기 위한 방법이다.</p><p>또한, <code class="language-plaintext highlighter-rouge">CheckedException</code> 중 복구가 불가능한 예외가 잡혔다면 어쩔 수 없이 의미없는 <code class="language-plaintext highlighter-rouge">try-catch</code>문을 추가해야하는데, 이때 <code class="language-plaintext highlighter-rouge">UncheckedException</code>으로 전환해서 던져버릴 수도 있다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
</pre><td class="rouge-code"><pre><span class="k">try</span><span class="o">{</span>
	<span class="o">...</span>
<span class="o">}</span>
<span class="k">catch</span><span class="o">(</span><span class="nc">SQLException</span> <span class="n">e</span><span class="o">){</span>
	<span class="k">throw</span> <span class="nf">DuplicateUserIdException</span><span class="o">();</span>
<span class="o">}</span>
</pre></table></code></div></div><h4 id="메소드에-예외-선언하기-throws">메소드에 예외 선언하기 throws</h4><p><code class="language-plaintext highlighter-rouge">throws</code> 키워드로 메소드에 예외를 선언할 수 있다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
</pre><td class="rouge-code"><pre><span class="kt">void</span> <span class="nf">method</span><span class="o">()</span> <span class="kd">throws</span> <span class="nc">Exception1</span><span class="o">,</span> <span class="nc">Exception2</span><span class="o">,</span> <span class="o">...</span> <span class="o">,</span> <span class="nc">ExceptionN</span><span class="o">{</span>
    <span class="o">...</span>
<span class="o">}</span>
</pre></table></code></div></div><p>이렇게 메소드의 선언부에 예외를 선언함으로써 해당 메소드에서 어떠한 예외가 처리되어야 하는지 직관적으로 파악할 수 있다.</p><p>하지만 이렇게 메소드에 예외를 선언한다고 해서 예외가 처리되는 것은 아니고, 해당 메소드를 <strong>호출한 메소드에게 예외를 던져서 예외처리를 떠넘기는 것</strong>이다.</p><p>단순히 예외를 넘길 뿐이므로 어느 한 곳에서도 예외처리를 해주지 않으면 결국 main 메소드에게 예외가 넘어가 프로그램이 종료된다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
</pre><td class="rouge-code"><pre><span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="kd">throws</span> <span class="nc">Exception</span> <span class="o">{</span>
    <span class="n">method1</span><span class="o">();</span>
<span class="o">}</span>
<span class="kd">static</span> <span class="kt">void</span> <span class="nf">method1</span><span class="o">()</span> <span class="kd">throws</span> <span class="nc">Exception</span> <span class="o">{</span>
    <span class="n">method2</span><span class="o">();</span>
<span class="o">}</span>
<span class="kd">static</span> <span class="kt">void</span> <span class="nf">method2</span><span class="o">()</span> <span class="kd">throws</span> <span class="nc">Exception</span> <span class="o">{</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nf">Exception</span><span class="o">(</span><span class="s">"method2()에서 예외 발생"</span><span class="o">);</span>
<span class="o">}</span>
</pre></table></code></div></div><div lang="console" class="language-console highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
</pre><td class="rouge-code"><pre><span class="go">Exception in thread "main" java.lang.Exception: method2()에서 예외 발생
	at com.example.javastudy.week9.ExceptionTest.method2(ExceptionTest.java:11)
	at com.example.javastudy.week9.ExceptionTest.method1(ExceptionTest.java:8)
	at com.example.javastudy.week9.ExceptionTest.main(ExceptionTest.java:5)
</span></pre></table></code></div></div><p>실행 결과를 보면, 프로그램 실행 중 <code class="language-plaintext highlighter-rouge">java.lang.Exception</code>이 발생하여 비정상적으로 종료되었다는 사실과 예외 발생 시 <code class="language-plaintext highlighter-rouge">call stack</code>의 내용을 알 수 있다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
</pre><td class="rouge-code"><pre><span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="o">{</span>
    <span class="k">try</span> <span class="o">{</span>
        <span class="n">method1</span><span class="o">();</span>
    <span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="nc">Exception</span> <span class="n">e</span><span class="o">)</span> <span class="o">{</span>
        <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"main 메소드에서 대신 예외처리"</span><span class="o">);</span>
    <span class="o">}</span>
<span class="o">}</span>
<span class="kd">static</span> <span class="kt">void</span> <span class="nf">method1</span><span class="o">()</span> <span class="kd">throws</span> <span class="nc">Exception</span> <span class="o">{</span>
    <span class="n">method2</span><span class="o">();</span>
<span class="o">}</span>
<span class="kd">static</span> <span class="kt">void</span> <span class="nf">method2</span><span class="o">()</span> <span class="kd">throws</span> <span class="nc">Exception</span> <span class="o">{</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nf">Exception</span><span class="o">(</span><span class="s">"method2()에서 예외 발생"</span><span class="o">);</span>
<span class="o">}</span>
</pre></table></code></div></div><p>이렇게 예외를 main에서 처리하거나 method2()를 호출하는 method1()에서 처리할 수도 있다.</p><h4 id="finally-블럭">finally 블럭</h4><p><code class="language-plaintext highlighter-rouge">finally</code>는 try-catch문에서 예외의 발생여부와 상관없이 실행되어야 할 코드를 포함하는 목적으로 사용한다. try-catch문의 맨 끝에 한 번만 선언할 수 있기때문에, <strong>try-catch-finally</strong>의 순서로 구성된다.</p><p>따라서 finally 블럭은 예외의 발생하던 말던 실행된다. 심지어 try 블럭이나 catch 블럭에 <code class="language-plaintext highlighter-rouge">return</code>문이 있더라도 finally문이 실행된다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
</pre><td class="rouge-code"><pre><span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="o">{</span>
    <span class="n">method</span><span class="o">();</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"method1()가 복귀한 후 실행될 문장"</span><span class="o">);</span>
<span class="o">}</span>
<span class="kd">static</span> <span class="kt">void</span> <span class="nf">method</span><span class="o">(){</span>
    <span class="k">try</span> <span class="o">{</span>
        <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"try block"</span><span class="o">);</span>
        <span class="k">return</span><span class="o">;</span>
    <span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="nc">Exception</span> <span class="n">e</span><span class="o">)</span> <span class="o">{</span>
        <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"catch block"</span><span class="o">);</span>
    <span class="o">}</span><span class="k">finally</span><span class="o">{</span>
        <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"finally block"</span><span class="o">);</span>
    <span class="o">}</span>
<span class="o">}</span>
</pre></table></code></div></div><div lang="console" class="language-console highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
</pre><td class="rouge-code"><pre><span class="go">try block
finally block
method1()가 복귀한 후 실행될 문장
</span></pre></table></code></div></div><p>그렇기 때문에 <strong>finally 블럭 내에서 return문을 사용하는 것은 안티패턴</strong>이므로 사용하지 않아야 한다. 만약 try문과 catch문에서 return을 호출하고 싶어도 항상 finally의 return이 호출되기 때문에 프로그램이 의도치 않은 흐름으로 동작할 수 있기 때문이다.</p><p>따라서 finally문에서는 흐름을 바꾸는 코드의 사용은 지양하고, 자원 반납이나 로깅 등의 용도로 사용해야 한다.</p><h4 id="자원-자동-반환-try-with-resource문">자원 자동 반환 try-with-resource문</h4><p>Java 7부터 자원 반납을 자동으로 해주는 <code class="language-plaintext highlighter-rouge">try-with-resource</code> 기능이 추가되었다. 원래 FileInput이나 DB 커넥션 등은 자원을 사용한 뒤 finally 블럭을 통해 자원을 반납했는데, 이 방식은 몇 가지 문제점을 가지고 있었다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
</pre><td class="rouge-code"><pre><span class="kt">void</span> <span class="nf">copy</span><span class="o">(</span><span class="nc">String</span> <span class="n">src</span><span class="o">,</span> <span class="nc">String</span> <span class="n">dest</span><span class="o">)</span> <span class="kd">throws</span> <span class="nc">IOException</span> <span class="o">{</span>
    <span class="nc">InputStream</span> <span class="n">in</span> <span class="o">=</span> <span class="kc">null</span><span class="o">;</span>
    <span class="nc">OutputStream</span> <span class="n">out</span> <span class="o">=</span> <span class="kc">null</span><span class="o">;</span>
    <span class="k">try</span><span class="o">{</span>
        <span class="n">in</span> <span class="o">=</span> <span class="k">new</span> <span class="nc">FileInputStream</span><span class="o">(</span><span class="n">src</span><span class="o">);</span>
        <span class="n">out</span> <span class="o">=</span> <span class="k">new</span> <span class="nc">FileOutputStream</span><span class="o">(</span><span class="n">dest</span><span class="o">);</span>
        <span class="kt">byte</span><span class="o">[]</span> <span class="n">buffer</span> <span class="o">=</span> <span class="k">new</span> <span class="kt">byte</span><span class="o">[</span><span class="mi">1024</span><span class="o">];</span>
        <span class="kt">int</span> <span class="n">n</span><span class="o">;</span>
        <span class="k">while</span><span class="o">((</span><span class="n">n</span> <span class="o">=</span> <span class="n">in</span><span class="o">.</span><span class="na">read</span><span class="o">(</span><span class="n">buffer</span><span class="o">))&gt;=</span><span class="mi">0</span><span class="o">)</span>
            <span class="n">out</span><span class="o">.</span><span class="na">write</span><span class="o">(</span><span class="n">buffer</span><span class="o">,</span> <span class="mi">0</span><span class="o">,</span> <span class="n">n</span><span class="o">);</span>
    <span class="o">}</span><span class="k">finally</span><span class="o">{</span>
        <span class="k">if</span><span class="o">(</span><span class="n">in</span> <span class="o">!=</span> <span class="kc">null</span><span class="o">)</span> <span class="n">in</span><span class="o">.</span><span class="na">close</span><span class="o">();</span>
        <span class="k">if</span><span class="o">(</span><span class="n">out</span> <span class="o">!=</span> <span class="kc">null</span><span class="o">)</span> <span class="n">out</span><span class="o">.</span><span class="na">close</span><span class="o">();</span>
    <span class="o">}</span>
<span class="o">}</span>
</pre></table></code></div></div><p>위 코드는 src로 받은 파일의 내용을 dest 파일로 복사하는 copy() 메소드를 나타낸다. 이 코드는 컴파일 에러가 잡히지 않지만, 문제점이 존재한다.</p><p>바로 finally 블럭에 존재하는 <code class="language-plaintext highlighter-rouge">close()</code>에서 예외가 발생할 수도 있다는 점이다. 만약 <code class="language-plaintext highlighter-rouge">in.close()</code>에서 exception이 발생한다면 <code class="language-plaintext highlighter-rouge">out.close()</code>는 실행되지 않는다. 이건 위 아래 순서를 바꿔도 마찬가지일 것이다.</p><p>그렇다면 finally 블럭 안에서도 try-catch를 통해 예외를 잡아주어야 할 것이다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
</pre><td class="rouge-code"><pre><span class="k">finally</span><span class="o">{</span>
    <span class="k">if</span><span class="o">(</span><span class="n">in</span> <span class="o">!=</span> <span class="kc">null</span><span class="o">){</span>
        <span class="k">try</span><span class="o">{</span>
            <span class="n">in</span><span class="o">.</span><span class="na">close</span><span class="o">();</span>
        <span class="o">}</span><span class="k">catch</span><span class="o">(</span><span class="nc">IOException</span> <span class="n">e</span><span class="o">){</span>
            <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"catch IOException in in.close()"</span><span class="o">);</span>
        <span class="o">}</span>
    <span class="o">}</span>
    <span class="k">if</span><span class="o">(</span><span class="n">out</span> <span class="o">!=</span> <span class="kc">null</span><span class="o">){</span>
        <span class="k">try</span><span class="o">{</span>
            <span class="n">out</span><span class="o">.</span><span class="na">close</span><span class="o">();</span>
        <span class="o">}</span><span class="k">catch</span><span class="o">(</span><span class="nc">IOException</span> <span class="n">e</span><span class="o">){</span>
            <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"catch IOException in out.close()"</span><span class="o">);</span>
        <span class="o">}</span>
    <span class="o">}</span>
<span class="o">}</span>
</pre></table></code></div></div><p>자, finally 블럭에도 각각 try-catch를 통해 예외처리를 해주었다. 근데 이 코드도 문제가 있다. <code class="language-plaintext highlighter-rouge">in.close()</code>에서 <code class="language-plaintext highlighter-rouge">IOException</code>이 아니라 <code class="language-plaintext highlighter-rouge">RuntimeException</code>이 발생한다면? 이런 경우에도 처음 코드처럼 밑에 있는 <code class="language-plaintext highlighter-rouge">out.close()</code>가 실행되지 않는다.</p><p>그래서 이 것까지 고려하면 코드를 이렇게 짜야한다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
</pre><td class="rouge-code"><pre><span class="kt">void</span> <span class="nf">copy</span><span class="o">(</span><span class="nc">String</span> <span class="n">src</span><span class="o">,</span> <span class="nc">String</span> <span class="n">dest</span><span class="o">)</span> <span class="kd">throws</span> <span class="nc">IOException</span> <span class="o">{</span>
    <span class="nc">InputStream</span> <span class="n">in</span> <span class="o">=</span> <span class="kc">null</span><span class="o">;</span>
    <span class="nc">OutputStream</span> <span class="n">out</span> <span class="o">=</span> <span class="kc">null</span><span class="o">;</span>
    <span class="k">try</span><span class="o">{</span>
        <span class="n">out</span> <span class="o">=</span> <span class="k">new</span> <span class="nc">FileOutputStream</span><span class="o">(</span><span class="n">dest</span><span class="o">);</span>
        <span class="k">try</span><span class="o">{</span>
            <span class="n">in</span> <span class="o">=</span> <span class="k">new</span> <span class="nc">FileInputStream</span><span class="o">(</span><span class="n">src</span><span class="o">);</span>
            <span class="kt">byte</span><span class="o">[]</span> <span class="n">buffer</span> <span class="o">=</span> <span class="k">new</span> <span class="kt">byte</span><span class="o">[</span><span class="mi">1024</span><span class="o">];</span>
            <span class="kt">int</span> <span class="n">n</span><span class="o">;</span>
            <span class="k">while</span><span class="o">((</span><span class="n">n</span> <span class="o">=</span> <span class="n">in</span><span class="o">.</span><span class="na">read</span><span class="o">(</span><span class="n">buffer</span><span class="o">))</span> <span class="o">&gt;=</span><span class="mi">0</span> <span class="o">)</span>
                <span class="n">out</span><span class="o">.</span><span class="na">write</span><span class="o">(</span><span class="n">buffer</span><span class="o">,</span> <span class="mi">0</span><span class="o">,</span> <span class="n">n</span><span class="o">);</span>
        <span class="o">}</span><span class="k">finally</span><span class="o">{</span>
            <span class="k">if</span> <span class="o">(</span><span class="n">in</span> <span class="o">!=</span> <span class="kc">null</span><span class="o">)</span> <span class="o">{</span>
                <span class="k">try</span><span class="o">{</span>
                    <span class="n">in</span><span class="o">.</span><span class="na">close</span><span class="o">();</span>
                <span class="o">}</span><span class="k">catch</span><span class="o">(</span><span class="nc">IOException</span> <span class="n">e</span><span class="o">){</span>
                    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"catch IOException in in.close()"</span><span class="o">);</span>
                <span class="o">}</span>
            <span class="o">}</span>
        <span class="o">}</span>
    <span class="o">}</span><span class="k">finally</span><span class="o">{</span>
        <span class="k">if</span> <span class="o">(</span><span class="n">out</span> <span class="o">!=</span> <span class="kc">null</span><span class="o">)</span> <span class="o">{</span>
            <span class="k">try</span><span class="o">{</span>
                <span class="n">out</span><span class="o">.</span><span class="na">close</span><span class="o">();</span>
            <span class="o">}</span><span class="k">catch</span><span class="o">(</span><span class="nc">IOException</span> <span class="n">e</span><span class="o">){</span>
                <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"catch IOException in out.close()"</span><span class="o">);</span>
            <span class="o">}</span>
        <span class="o">}</span>
    <span class="o">}</span>
<span class="o">}</span>
</pre></table></code></div></div><p>이런 말하기 뭐하지만 코드가 정말 더럽다. 하지만 Java 7 이후로는 <code class="language-plaintext highlighter-rouge">try-with-resource</code>문을 사용하여 간단하게 처리할 수 있게 되었다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
</pre><td class="rouge-code"><pre><span class="kt">void</span> <span class="nf">copy</span><span class="o">(</span><span class="nc">String</span> <span class="n">src</span><span class="o">,</span> <span class="nc">String</span> <span class="n">dest</span><span class="o">)</span> <span class="kd">throws</span> <span class="nc">IOException</span> <span class="o">{</span>
    <span class="k">try</span><span class="o">(</span><span class="nc">InputStream</span> <span class="n">in</span> <span class="o">=</span> <span class="k">new</span> <span class="nc">FileInputStream</span><span class="o">(</span><span class="n">src</span><span class="o">);</span>
        <span class="nc">OutputStream</span> <span class="n">out</span> <span class="o">=</span> <span class="k">new</span> <span class="nc">FileOutputStream</span><span class="o">(</span><span class="n">dest</span><span class="o">)){</span>
        <span class="kt">byte</span><span class="o">[]</span> <span class="n">buffer</span> <span class="o">=</span> <span class="k">new</span> <span class="kt">byte</span><span class="o">[</span><span class="mi">1024</span><span class="o">];</span>
        <span class="kt">int</span> <span class="n">n</span><span class="o">;</span>
        <span class="k">while</span><span class="o">((</span><span class="n">n</span> <span class="o">=</span> <span class="n">in</span><span class="o">.</span><span class="na">read</span><span class="o">(</span><span class="n">buffer</span><span class="o">))</span> <span class="o">&gt;=</span> <span class="mi">0</span><span class="o">)</span>
            <span class="n">out</span><span class="o">.</span><span class="na">write</span><span class="o">(</span><span class="n">buffer</span><span class="o">,</span> <span class="mi">0</span><span class="o">,</span> <span class="n">n</span><span class="o">);</span>
    <span class="o">}</span>
<span class="o">}</span>
</pre></table></code></div></div><p>정말 간단하고 직관적이지 않은가? 위 코드에서는 예외를 던지고 있지만 copy()에서 처리하고 싶으면 catch 블럭을 추가해서 예외를 잡아주면 된다.</p><p>또한 finally블럭을 추가하면 자동 자원 반납 후 finally 블럭 실행하도록 할 수도 있다. 왜냐하면 <code class="language-plaintext highlighter-rouge">try-with-resource문</code>은 <strong>내부적으로 catch문을 추가</strong>해서 자동으로 자원반납해주기때문에 finally 블럭도 사용할 수 있다.</p><p>그런데, 내부적으로 catch 블럭을 추가한다면 예외 상황에만 자원이 반납되는거 아닌가? 하는 의문이 들 수 있는데, 컴파일된 파일을 보면 catch문 안과 밖에 두 개의 <code class="language-plaintext highlighter-rouge">close()</code>가 있어서 예외가 발생하던 안하던 자원을 반납하도록 구성되어 있다.</p><p>try-with-resource문은 개발자의 실수를 줄여주고 코드를 훨씬 직관적이고 간단하게 구성할 수 있도록 한다. 따라서 Java 7 이후의 환경이라면 자원 반납 시 finally문 대신 try-with-resource문을 사용할 것을 적극 권장한다.</p><h4 id="예외처리-비용">예외처리 비용</h4><p>예외를 사용한다는 자체가 비용이 비싸다고 할 수 있다. <code class="language-plaintext highlighter-rouge">try-catch</code>를 동작하면서 발생하는 검사들도 하나의 원인이지만, <code class="language-plaintext highlighter-rouge">Throwable</code> 클래스의 생성자에 있는 <code class="language-plaintext highlighter-rouge">fillInStackTrace()</code> 메소드가 주 원인이다.</p><p>이 메소드는 예외가 발생한 메소드의 <code class="language-plaintext highlighter-rouge">Stack Trace</code>를 모두 출력해주기 때문에 메모리를 많이 잡아먹는다. 따라서 로직으로 충분히 처리할 수 있다면 <code class="language-plaintext highlighter-rouge">Exception</code>을 사용하지 않는 것이 좋다.</p><h3 id="자바가-제공하는-예외-계층-구조"><strong>자바가 제공하는 예외 계층 구조</strong></h3><p>자바에서는 실행 시 발생할 수 있는 오류(Exception &amp; Error)를 클래스로 정의하고 있다. 따라서 오류 또한 <code class="language-plaintext highlighter-rouge">Object</code> 클래스를 상속받고 있음을 추측할 수 있고, 실제 상속 계층도는 아래와 같다.</p><p><img data-proofer-ignore data-src="https://user-images.githubusercontent.com/70433341/104199159-6d2f1200-546a-11eb-89bd-207c4d2c149f.png" /></p><p>출처 : <a href="https://catch-me-java.tistory.com/46">https://catch-me-java.tistory.com/46</a></p><p>맨 위에 자바의 최상위 클래스인 <code class="language-plaintext highlighter-rouge">Object</code> 클래스가 있고 그 것을 상속하는 예외 클래스의 최상위 클래스인 <code class="language-plaintext highlighter-rouge">Throwable</code> 클래스가 있다. <code class="language-plaintext highlighter-rouge">Throwable</code> 클래스는 모든 <code class="language-plaintext highlighter-rouge">Exception</code>과 <code class="language-plaintext highlighter-rouge">Error</code>의 부모 클래스이다.</p><p>예외 처리 시 많이 사용하는 메소드인 <code class="language-plaintext highlighter-rouge">printStackTrace()</code>와 <code class="language-plaintext highlighter-rouge">getMessage()</code>가 바로 <code class="language-plaintext highlighter-rouge">Throwable</code> 클래스의 메소드이다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
</pre><td class="rouge-code"><pre><span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">){</span>
    <span class="k">try</span> <span class="o">{</span>
        <span class="k">throw</span> <span class="k">new</span> <span class="nf">Exception</span><span class="o">(</span><span class="s">"예외 메시지 작성"</span><span class="o">);</span>
    <span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="nc">Exception</span> <span class="n">e</span><span class="o">)</span> <span class="o">{</span>
        <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"에러 메시지 : "</span> <span class="o">+</span> <span class="n">e</span><span class="o">.</span><span class="na">getMessage</span><span class="o">());</span>
        <span class="n">e</span><span class="o">.</span><span class="na">printStackTrace</span><span class="o">();</span>
    <span class="o">}</span>
    <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"정상 종료"</span><span class="o">);</span>
<span class="o">}</span>
</pre></table></code></div></div><div lang="console" class="language-console highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
</pre><td class="rouge-code"><pre><span class="go">에러 메시지 : 예외 메시지 작성
정상 종료
java.lang.Exception: 예외 메시지 작성
	at com.example.javastudy.week9.ExceptionTest.main(ExceptionTest.java:8)

Process finished with exit code 0
</span></pre></table></code></div></div><p>이렇게 예외타입의 매개변수에 <code class="language-plaintext highlighter-rouge">printStackTrace()</code>를 호출하게 되면 예외가 발생하기 까지의 이력을 출력해준다. 이 이력은 어디에 저장되었다가 출력되는 것일까?</p><p>1주차에서 배운 JVM의 구조를 떠올려보면, 메소드 실행 시 메모리의 <code class="language-plaintext highlighter-rouge">Stack</code> 영역에 <code class="language-plaintext highlighter-rouge">Stack Frame</code>이 쌓이게 된다. 즉, Stack 영역은 Stack Frame을 저장하는 영역이며, JVM은 오직 Stack Frame을 <code class="language-plaintext highlighter-rouge">push</code>하고 <code class="language-plaintext highlighter-rouge">pop</code>하는 작업을 한다.</p><p>예외가 발생 시에 출력되는 Stack Trace의 각 라인은 Stack Frame을 표현하는 것이며, 메모리 영역 Stack에 쌓여있는 Stack Frame들을 pop()하며 출력하는 것이다.</p><p><br /> 예외 클래스의 최상위 클래스는 항상 <code class="language-plaintext highlighter-rouge">Throwable</code> 클래스이지만, 세부적으로 들어가 보면 이를 상속하는 예외는 크게 세 가지 부류로 나뉜다.</p><ol><li>Error 클래스를 상속하는 예외 클래스<li>RuntimeException 클래스를 상속하는 Exception 클래스<li>RuntimeException 클래스를 상속하지 않는 Exception 클래스</ol><p>앞서 Error와 Exception의 차이는 언급했기 때문에 알고 있지만, Exception을 상속하는 클래스들 중에서도 <code class="language-plaintext highlighter-rouge">RuntimeException</code>을 상속한 클래스와 그렇지 않은 클래스 간에는 어떠한 차이가 존재할까?</p><h3 id="runtimeexception과-re가-아닌-것의-차이는"><strong>RuntimeException과 RE가 아닌 것의 차이는?</strong></h3><p><code class="language-plaintext highlighter-rouge">RuntimeException</code>을 상속한 클래스는 <code class="language-plaintext highlighter-rouge">UncheckedException</code>이라고 하고, <code class="language-plaintext highlighter-rouge">RuntimeException</code>을 상속하지 않은 <code class="language-plaintext highlighter-rouge">Exception</code> 클래스는 <code class="language-plaintext highlighter-rouge">CheckedException</code>이라고 한다.</p><h4 id="checkedexception"><strong>CheckedException</strong></h4><p><code class="language-plaintext highlighter-rouge">CheckedException</code>은 컴파일 시점에 확인될 수 있는(체크될 수 있는) 예외를 말한다. 즉, 프로그램 내부의 로직이 아닌 프로그램의 제어 밖에서 발생하는 오류를 의미한다. 따라서 <code class="language-plaintext highlighter-rouge">CheckedException</code>이 발생하는 코드를 실행하기 위해서는 <strong>반드시 예외처리(try-catch나 throws)를 해줘야 한다.</strong></p><h4 id="checkedexception의-대표적인-예시">CheckedException의 대표적인 예시</h4><ol><li><p>IOException<br /> <code class="language-plaintext highlighter-rouge">IOException</code>은 input이나 output 작업이 실패할 때 발생하는 예외이다. <code class="language-plaintext highlighter-rouge">IOException</code>를 상속한 클래스로는 <code class="language-plaintext highlighter-rouge">FileNotFoundException</code>, <code class="language-plaintext highlighter-rouge">MalformedURLException</code> 등이 있다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
</pre><td class="rouge-code"><pre> <span class="kd">public</span> <span class="kd">class</span> <span class="nc">IOExceptionExample</span> <span class="o">{</span>
     <span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="o">{</span>
         <span class="k">try</span> <span class="o">(</span><span class="nc">FileReader</span> <span class="n">reader</span> <span class="o">=</span> <span class="k">new</span> <span class="nc">FileReader</span><span class="o">(</span><span class="s">"invalidFileName"</span><span class="o">))</span> <span class="o">{</span>
         <span class="o">/...</span>
         <span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="nc">FileNotFoundException</span> <span class="n">e</span><span class="o">)</span> <span class="o">{</span>
             <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"FileNotFoundException 발생"</span><span class="o">);</span>
         <span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="nc">IOException</span> <span class="n">e</span><span class="o">)</span> <span class="o">{</span>
             <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"IOException 발생"</span><span class="o">);</span>
         <span class="o">}</span>
     <span class="o">}</span>
 <span class="o">}</span>
</pre></table></code></div></div><li><p>ParseException<br /> <code class="language-plaintext highlighter-rouge">ParseException</code>은 텍스트를 파싱하는 작업이 실패할 때 발생한다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
</pre><td class="rouge-code"><pre> <span class="kd">public</span> <span class="kd">class</span> <span class="nc">ParseExceptionExample</span> <span class="o">{</span>
     <span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="o">{</span>
         <span class="k">try</span> <span class="o">{</span>
             <span class="k">new</span> <span class="nf">SimpleDateFormat</span><span class="o">(</span><span class="s">"MM-dd-yyyy"</span><span class="o">).</span><span class="na">parse</span><span class="o">(</span><span class="s">"test"</span><span class="o">);</span>
         <span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="nc">ParseException</span> <span class="n">e</span><span class="o">)</span> <span class="o">{</span>
             <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"ParseException 발생"</span><span class="o">);</span>
         <span class="o">}</span>
     <span class="o">}</span>
 <span class="o">}</span>
</pre></table></code></div></div><li><p>InterruptedException<br /> <code class="language-plaintext highlighter-rouge">InterruptedException</code>은 다른 쓰레드가 <code class="language-plaintext highlighter-rouge">wating</code> 혹은 <code class="language-plaintext highlighter-rouge">timed_wating</code> 상태인 쓰레드에 <code class="language-plaintext highlighter-rouge">interrupt</code> 할 때 발생하는 예외이다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
</pre><td class="rouge-code"><pre> <span class="kd">public</span> <span class="kd">class</span> <span class="nc">InterruptedExceptionExample</span> <span class="o">{</span>
     <span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="o">{</span>
         <span class="n">subThread</span> <span class="n">subThread</span> <span class="o">=</span> <span class="k">new</span> <span class="n">subThread</span><span class="o">();</span>
         <span class="n">subThread</span><span class="o">.</span><span class="na">start</span><span class="o">();</span>
         <span class="n">subThread</span><span class="o">.</span><span class="na">interrupt</span><span class="o">();</span>
     <span class="o">}</span>

     <span class="kd">public</span> <span class="kd">static</span> <span class="kd">class</span> <span class="nc">subThread</span> <span class="kd">extends</span> <span class="nc">Thread</span> <span class="o">{</span>
         <span class="nd">@Override</span>
         <span class="kd">public</span> <span class="kt">void</span> <span class="nf">run</span><span class="o">()</span> <span class="o">{</span>
         <span class="k">try</span> <span class="o">{</span>
             <span class="nc">Thread</span><span class="o">.</span><span class="na">sleep</span><span class="o">(</span><span class="mi">10000</span><span class="o">);</span> <span class="c1">// 10초간 sleep</span>
         <span class="o">}</span> <span class="k">catch</span> <span class="o">(</span><span class="nc">InterruptedException</span> <span class="n">e</span><span class="o">)</span> <span class="o">{</span>
             <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="s">"InterruptedException 발생"</span><span class="o">);</span>
         <span class="o">}</span>
         <span class="o">}</span>
     <span class="o">}</span>
 <span class="o">}</span>
</pre></table></code></div></div></ol><h4 id="uncheckedexception"><strong>UncheckedException</strong></h4><p><code class="language-plaintext highlighter-rouge">UncheckedException</code>은 프로그램 상의 문제로 인해 실행 시(Runtime)에 발생하는 오류를 의미한다. 자바는 컴파일 시점에 <code class="language-plaintext highlighter-rouge">UncheckedException</code>을 확인하지 않기 때문에 <strong>예외 처리를 강제하지 않는다.</strong> 따라서 이 것을 핸들링할지 말지는 사용자가 정해야 한다.</p><h4 id="uncheckedexception의-대표적인-예시">UncheckedException의 대표적인 예시</h4><ol><li>NullPointException<br /> <code class="language-plaintext highlighter-rouge">NullPointException</code>은 객체를 필요로 하는 곳에서 null값을 참조할 때 발생한다.<div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
</pre><td class="rouge-code"><pre> <span class="kd">public</span> <span class="kd">class</span> <span class="nc">Example</span> <span class="o">{</span>
     <span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="o">{</span>
         <span class="nc">String</span> <span class="n">text</span> <span class="o">=</span> <span class="kc">null</span><span class="o">;</span>
         <span class="n">text</span><span class="o">.</span><span class="na">length</span><span class="o">();</span> <span class="c1">// NullPointerException 발생</span>
     <span class="o">}</span>
 <span class="o">}</span>
</pre></table></code></div></div><li><p>ArrayIndexOutOfBoundsException<br /> <code class="language-plaintext highlighter-rouge">ArrayIndexOutOfBoundsException</code>은 범위를 넘어선 잘 못된 인덱스에 접근할 때 발생한다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
</pre><td class="rouge-code"><pre> <span class="kd">public</span> <span class="kd">class</span> <span class="nc">Example</span> <span class="o">{</span>
     <span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="o">{</span>
         <span class="kt">int</span><span class="o">[]</span> <span class="n">numbers</span> <span class="o">=</span> <span class="k">new</span> <span class="kt">int</span><span class="o">[</span><span class="mi">5</span><span class="o">];</span>
         <span class="kt">int</span> <span class="n">number</span> <span class="o">=</span> <span class="n">numbers</span><span class="o">[</span><span class="mi">5</span><span class="o">];</span> <span class="c1">// ArrayIndexOutOfBoundsException 발생</span>
     <span class="o">}</span>
 <span class="o">}</span>   
</pre></table></code></div></div><li><p>StringIndexOutOfBoundsException<br /> <code class="language-plaintext highlighter-rouge">StringIndexOutOfBoundsException</code>은 텍스트의 길이보다 크거나 같은 인덱스에 접근할 때 발생한다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
</pre><td class="rouge-code"><pre> <span class="kd">public</span> <span class="kd">class</span> <span class="nc">Example</span> <span class="o">{</span>
     <span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="o">{</span>
         <span class="nc">String</span> <span class="n">text</span> <span class="o">=</span> <span class="s">"Test text"</span><span class="o">;</span>
         <span class="n">text</span><span class="o">.</span><span class="na">charAt</span><span class="o">(</span><span class="mi">9</span><span class="o">);</span> <span class="c1">// StringIndexOutOfBoundsException 발생</span>
     <span class="o">}</span>
 <span class="o">}</span>
</pre></table></code></div></div><li><p>NumberFormatException<br /> <code class="language-plaintext highlighter-rouge">NumberFormatException</code>은 텍스트가 변환하고자하는 숫자 데이터 형식에 맞지 않을 때 발생한다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
</pre><td class="rouge-code"><pre> <span class="kd">public</span> <span class="kd">class</span> <span class="nc">Example</span> <span class="o">{</span>
     <span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="o">{</span>
         <span class="kt">int</span> <span class="n">number</span> <span class="o">=</span> <span class="nc">Integer</span><span class="o">.</span><span class="na">parseInt</span><span class="o">(</span><span class="s">"12Ab3C"</span><span class="o">);</span> <span class="c1">// NumberFormatException 발생</span>
     <span class="o">}</span>
 <span class="o">}</span>
</pre></table></code></div></div><li><p>ArithmeticException<br /> <code class="language-plaintext highlighter-rouge">ArithmeticException</code>은 산술연산 시 해당 연산이 잘못된 조건일 때 발생한다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
</pre><td class="rouge-code"><pre> <span class="kd">public</span> <span class="kd">class</span> <span class="nc">Example</span> <span class="o">{</span>
     <span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="o">{</span>
         <span class="nc">System</span><span class="o">.</span><span class="na">out</span><span class="o">.</span><span class="na">println</span><span class="o">(</span><span class="mi">5</span><span class="o">/</span><span class="mi">0</span><span class="o">);</span> <span class="c1">// ArithmeticException 발생</span>
     <span class="o">}</span>
 <span class="o">}</span>
</pre></table></code></div></div><li><p>ClassCastException<br /> <code class="language-plaintext highlighter-rouge">ClassCastException</code>은 객체를 다운캐스팅할 때, 잘못된 인스턴스를 캐스팅하여 발생한다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
</pre><td class="rouge-code"><pre> <span class="kd">class</span> <span class="nc">Monster</span><span class="o">{}</span>
 <span class="kd">class</span> <span class="nc">Digimon</span> <span class="kd">extends</span> <span class="nc">Monster</span><span class="o">{}</span>
 <span class="kd">class</span> <span class="nc">Pocketmon</span> <span class="kd">extends</span> <span class="nc">Monster</span><span class="o">{}</span>

 <span class="kd">public</span> <span class="kd">class</span> <span class="nc">ExceptionTest</span> <span class="o">{</span>
     <span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">){</span>
         <span class="nc">Monster</span> <span class="n">a</span> <span class="o">=</span> <span class="k">new</span> <span class="nc">Digimon</span><span class="o">();</span>
         <span class="nc">Pocketmon</span> <span class="n">b</span> <span class="o">=</span> <span class="o">(</span><span class="nc">Pocketmon</span><span class="o">)</span> <span class="n">a</span><span class="o">;</span> <span class="c1">// ClassCastException 발생</span>
     <span class="o">}</span>
 <span class="o">}</span>
</pre></table></code></div></div><li><p>IllegalArgumentException<br /> <code class="language-plaintext highlighter-rouge">IllegalArgumentException</code>은 메소드에 잘못된 변수를 전달할 때 발생한다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
</pre><td class="rouge-code"><pre> <span class="kd">public</span> <span class="kd">class</span> <span class="nc">Example</span> <span class="o">{</span>
     <span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="o">{</span>
         <span class="nc">Thread</span><span class="o">.</span><span class="na">sleep</span><span class="o">(-</span><span class="mi">1</span><span class="o">);</span> <span class="c1">// IllegalArgumentException 발생</span>
     <span class="o">}</span>
 <span class="o">}</span>
</pre></table></code></div></div><li><p>IllegalStateException<br /> <code class="language-plaintext highlighter-rouge">IllegalStateException</code>은 메소드를 잘못된 시점에 호출했을 때 발생한다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
</pre><td class="rouge-code"><pre> <span class="kd">public</span> <span class="kd">class</span> <span class="nc">Example</span> <span class="o">{</span>
     <span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="o">{</span>
         <span class="nc">ListIterator</span><span class="o">&lt;</span><span class="nc">Object</span><span class="o">&gt;</span> <span class="n">it</span> <span class="o">=</span> <span class="k">new</span> <span class="nc">ArrayList</span><span class="o">&lt;&gt;().</span><span class="na">listIterator</span><span class="o">();</span>
         <span class="n">it</span><span class="o">.</span><span class="na">remove</span><span class="o">();</span> <span class="c1">// IllegalStateException 발생</span>
     <span class="o">}</span>
 <span class="o">}</span>
</pre></table></code></div></div></ol><p>이렇게 <code class="language-plaintext highlighter-rouge">UncheckedException</code>의 경우 컴파일러가 체크 해주지 않기 때문에, 혼란을 방지하기 위해서는 이 메소드에 <code class="language-plaintext highlighter-rouge">Exception</code>이 있다는 것을 알리는 편이 좋다.</p><p><code class="language-plaintext highlighter-rouge">javadoc</code>을 이용하면 이것을 간단하게 표시할 수 있다. <code class="language-plaintext highlighter-rouge">javadoc</code>의 <code class="language-plaintext highlighter-rouge">@throws</code>와 <code class="language-plaintext highlighter-rouge">@exception</code> 키워드를 통해 메소드 내의 <code class="language-plaintext highlighter-rouge">Exception</code>에 대한 설명을 추가하도록 하자.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
</pre><td class="rouge-code"><pre><span class="cm">/** 
 * @throws Exception explanation
 * @exception IllegalArgumentException explanation
*/</span>
<span class="kd">public</span> <span class="kt">void</span> <span class="nf">method</span><span class="o">()</span> <span class="kd">throws</span> <span class="nc">Exception</span> <span class="o">{</span>
  <span class="k">throw</span> <span class="k">new</span> <span class="nf">IllegalArgumentException</span><span class="o">();</span>
<span class="o">}</span>
</pre></table></code></div></div><h4 id="exception을-분리한-이유">exception을 분리한 이유</h4><p>예외는 메소드의 파라미터나 리턴 타입만큼이나 중요한 공용 인터페이스 중 하나이다. 따라서 메소드를 호출하는 쪽은 해당 메소드가 어떤 예외를 발생시킬 수 있는지에 대해 반드시 알아야 한다.</p><p>따라서 Java는 <code class="language-plaintext highlighter-rouge">CheckedException</code>을 통해 해당 메소드가 발생시킬 수 있는 예외를 명시하도록 강제하고 있다. 그런데 <code class="language-plaintext highlighter-rouge">RuntimeExcepton</code>은 왜 예외를 명시하지 않아도 되는 것일까?</p><p><code class="language-plaintext highlighter-rouge">RuntimeException</code>은 프로그램 코드 상의 문제로 발생하는 예외이다.(개발자가 코드를 잘못짜서 발생) 따라서 메소드를 호출하는 쪽(클라이언트)에서 이 예외를 복구하거나 대처할 수 있을 거라고 기대하기 힘들다.</p><p>또한, <code class="language-plaintext highlighter-rouge">RuntimeException</code>은 프로그램 어디에서나 빈번하게 등장할 수 있기때문에 매 번 모든 <code class="language-plaintext highlighter-rouge">RuntimeException</code>을 명시하도록 하는 것은 오히려 프로그램의 명확성을 떨어뜨릴 수 있다.</p><p>따라서 클라이언트가 <code class="language-plaintext highlighter-rouge">exception</code>을 적절히 대처할 수 있을 것이라고 예상되는 경우 <code class="language-plaintext highlighter-rouge">CheckedException</code>으로 만들고, 그렇지 않은 경우 <code class="language-plaintext highlighter-rouge">UncheckedException</code>으로 만드는 것이 좋다.</p><h4 id="uncheckedexception과-트렌잭션">UncheckedException과 트렌잭션?</h4><p>스터디를 진행하신 많은 분들의 과제에서 <code class="language-plaintext highlighter-rouge">UncheckedException</code>과 <code class="language-plaintext highlighter-rouge">CheckedException</code>에 대한 트렌잭션 처리에 관한 잘못된 정보가 있었다. 많은 포스트에서 <code class="language-plaintext highlighter-rouge">UncheckedException</code>이 발생하면 트렌잭션에 대해 <code class="language-plaintext highlighter-rouge">roll-back</code> 기능을 제공한다고 나와있는데, 이 것은 명백히 잘못된 정보이다.</p><p>이 것은 순수 자바 언어에서 지원하는 기능이 아니라, <code class="language-plaintext highlighter-rouge">spring framework</code>에서 기본 설정으로 제공하는 기능이다. 따라서 이 것을 Java에서 지원하는 기능이라고 오해해서는 안되겠다.</p><h3 id="커스텀한-예외-만드는-방법"><strong>커스텀한 예외 만드는 방법</strong></h3><h4 id="custom-checked-exception">Custom Checked Exception</h4><p><code class="language-plaintext highlighter-rouge">Exception</code> 클래스를 상속하면 <code class="language-plaintext highlighter-rouge">Custom Checked Exception</code> 클래스를 만들 수 있다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
</pre><td class="rouge-code"><pre><span class="cm">/**
 * this CustomException extends Exception and ....
 * @author yeoji
 */</span>
<span class="kd">class</span> <span class="nc">CustomException</span> <span class="kd">extends</span> <span class="nc">Exception</span> <span class="o">{</span>
    <span class="kd">public</span> <span class="nf">CustomException</span><span class="o">()</span> <span class="o">{</span>
    <span class="o">}</span>

    <span class="kd">public</span> <span class="nf">CustomException</span><span class="o">(</span><span class="nc">String</span> <span class="n">message</span><span class="o">)</span> <span class="o">{</span>
        <span class="kd">super</span><span class="o">(</span><span class="n">message</span><span class="o">);</span>
    <span class="o">}</span>

    <span class="kd">public</span> <span class="nf">CustomException</span><span class="o">(</span><span class="nc">String</span> <span class="n">message</span><span class="o">,</span> <span class="nc">Throwable</span> <span class="n">cause</span><span class="o">)</span> <span class="o">{</span>
        <span class="kd">super</span><span class="o">(</span><span class="n">message</span><span class="o">,</span> <span class="n">cause</span><span class="o">);</span>
    <span class="o">}</span>
<span class="o">}</span>
</pre></table></code></div></div><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
</pre><td class="rouge-code"><pre><span class="kd">public</span> <span class="kd">class</span> <span class="nc">ExceptionTest</span> <span class="o">{</span>
    <span class="kd">public</span> <span class="kd">static</span> <span class="kt">void</span> <span class="nf">main</span><span class="o">(</span><span class="nc">String</span><span class="o">[]</span> <span class="n">args</span><span class="o">)</span> <span class="kd">throws</span> <span class="nc">CustomException</span> <span class="o">{</span>
        <span class="n">method</span><span class="o">();</span>
    <span class="o">}</span>

    <span class="kd">static</span> <span class="kt">void</span> <span class="nf">method</span><span class="o">()</span> <span class="kd">throws</span> <span class="nc">CustomException</span> <span class="o">{</span>
        <span class="k">throw</span> <span class="k">new</span> <span class="nf">CustomException</span><span class="o">(</span><span class="s">"custom"</span><span class="o">,</span> <span class="k">new</span> <span class="nc">Exception</span><span class="o">());</span>
    <span class="o">}</span>
<span class="o">}</span>
</pre></table></code></div></div><div lang="console" class="language-console highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
</pre><td class="rouge-code"><pre><span class="go">Exception in thread "main" com.example.javastudy.week9.CustomException: custom
	at com.example.javastudy.week9.ExceptionTest.method1(ExceptionTest.java:11)
	at com.example.javastudy.week9.ExceptionTest.main(ExceptionTest.java:7)
Caused by: java.lang.Exception
	... 2 more
</span></pre></table></code></div></div><p>이 코드를 보면 <code class="language-plaintext highlighter-rouge">method()</code>에서 <code class="language-plaintext highlighter-rouge">CustomException</code>을 호출할 때 생성자에 예외 메시지와 함께 <code class="language-plaintext highlighter-rouge">cause exception</code>을 전달한 것을 알 수 있다. 만약 예외 메시지만 담아서 던질 경우, 예외 발생의 원인을 찾기 힘든 피상적인 예외가 될 수 있다.</p><p>따라서 커스텀 예외의 생성자 호출 시 근본 원인이 되는 cause exception을 함께 전달할 것을 권장한다.</p><blockquote><p>그러나 커스텀 예외가 root cause일 수도 있으니 필수는 아니고 권장사항일뿐이다.</p></blockquote><h4 id="custom-unchecked-exception">Custom Unchecked Exception</h4><p>마찬가지로 <code class="language-plaintext highlighter-rouge">RuntimeException</code>을 상속하면 <code class="language-plaintext highlighter-rouge">Custom Unchecked Exception</code> 클래스를 만들 수 있다.</p><div lang="java" class="language-java highlighter-rouge"><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
</pre><td class="rouge-code"><pre><span class="cm">/**
 * this CustomException extends RuntimeException and ....
 * @author yeoji
 */</span>
<span class="kd">class</span> <span class="nc">CustomException</span> <span class="kd">extends</span> <span class="nc">RuntimeException</span> <span class="o">{</span>
    <span class="kd">public</span> <span class="nf">CustomException</span><span class="o">()</span> <span class="o">{</span>
    <span class="o">}</span>

    <span class="kd">public</span> <span class="nf">CustomException</span><span class="o">(</span><span class="nc">String</span> <span class="n">message</span><span class="o">)</span> <span class="o">{</span>
        <span class="kd">super</span><span class="o">(</span><span class="n">message</span><span class="o">);</span>
    <span class="o">}</span>

    <span class="kd">public</span> <span class="nf">CustomException</span><span class="o">(</span><span class="nc">String</span> <span class="n">message</span><span class="o">,</span> <span class="nc">Throwable</span> <span class="n">cause</span><span class="o">)</span> <span class="o">{</span>
        <span class="kd">super</span><span class="o">(</span><span class="n">message</span><span class="o">,</span> <span class="n">cause</span><span class="o">);</span>
    <span class="o">}</span>
<span class="o">}</span>
</pre></table></code></div></div><h4 id="커스텀-예외-생성-시-고려-사항">커스텀 예외 생성 시 고려 사항</h4><ol><li><strong>Always Provide a Benefit</strong> <br /> 자바 표준 예외는 다양한 장점을 가진 기능들을 포함한다. 이미 JDK가 존재하는 예외들과 비교해 커스텀 예외가 가지는 장점이 없다면 커스텀 예외를 만드는 이유를 다시 생각해봐야 할 것이다.<li><strong>Follow the Naming Convention</strong><br /> 자바 표준 예외의 이름은 모두 Exception으로 끝나는 것을 알 수 있다. 이러한 네이밍 규칙은 자바 생태계 전체에 적용되므로 커스텀 예외 클래스도 이 네이밍 규칙을 따르는 것이 좋다.<li><strong>Provide javadoc Comments for Your Exception Class</strong><br /> 문서화되어 있지 않은 API는 사용하기 매우 어렵다. 협업을 하는 다른 개발자뿐 아니라 미래의 나를 위해서라도 javadoc에 커스텀 클래스의 발생 상황이나 의미를 기술해야 한다.<li><strong>Provide a Constructor That Sets the Cause</strong><br /> 커스텀 예외를 던지기 전에 표준 예외를 Catch하는 케이스가 꽤 많다. 이러한 예외는 오류를 분석하는데 중요한 정보가 포함되어 있으므로 cause exception을 유지해야 한다.</ol><h3 id="참조">참조</h3><p><a href="https://wisdom-and-record.tistory.com/46">https://wisdom-and-record.tistory.com/46</a><br /> <a href="https://catch-me-java.tistory.com/46">https://catch-me-java.tistory.com/46</a><br /> <a href="https://www.notion.so/3565a9689f714638af34125cbb8abbe8">https://www.notion.so/3565a9689f714638af34125cbb8abbe8</a><br /> <a href="https://yadon079.github.io/2021/java%20study%20halle/week-09">https://yadon079.github.io/2021/java%20study%20halle/week-09</a><br /> <a href="https://github.com/ByungJun25/study/tree/main/java/whiteship-study/9week">https://github.com/ByungJun25/study/tree/main/java/whiteship-study/9week</a></p></div><div class="post-tail-wrapper text-muted"><div class="post-meta mb-3"> <i class="far fa-folder-open fa-fw mr-1"></i> <a href='/categories/backend/'>Backend</a>, <a href='/categories/java/'>Java</a></div><div class="post-tags"> <i class="fa fa-tags fa-fw mr-1"></i> <a href="/tags/java/" class="post-tag no-text-decoration" >java</a> <a href="/tags/java-study/" class="post-tag no-text-decoration" >java study</a> <a href="/tags/%EC%9E%90%EB%B0%94/" class="post-tag no-text-decoration" >자바</a> <a href="/tags/%EC%9E%90%EB%B0%94-%EC%8A%A4%ED%84%B0%EB%94%94/" class="post-tag no-text-decoration" >자바 스터디</a></div><div class="post-tail-bottom d-flex justify-content-between align-items-center mt-3 pt-5 pb-2"><div class="license-wrapper"> This post is licensed under <a href="https://creativecommons.org/licenses/by/4.0/"> CC BY 4.0 </a> by the author.</div><div class="share-wrapper"> <span class="share-label text-muted mr-1">Share</span> <span class="share-icons"> <a href="https://twitter.com/intent/tweet?text=자바 스터디 09 - 예외 처리 - yeoji21&url=https://yeoji21.github.io/posts/javastudy09/" data-toggle="tooltip" data-placement="top" title="Twitter" target="_blank" rel="noopener" aria-label="Twitter"> <i class="fa-fw fab fa-twitter"></i> </a> <a href="https://www.facebook.com/sharer/sharer.php?title=자바 스터디 09 - 예외 처리 - yeoji21&u=https://yeoji21.github.io/posts/javastudy09/" data-toggle="tooltip" data-placement="top" title="Facebook" target="_blank" rel="noopener" aria-label="Facebook"> <i class="fa-fw fab fa-facebook-square"></i> </a> <a href="https://telegram.me/share?text=자바 스터디 09 - 예외 처리 - yeoji21&url=https://yeoji21.github.io/posts/javastudy09/" data-toggle="tooltip" data-placement="top" title="Telegram" target="_blank" rel="noopener" aria-label="Telegram"> <i class="fa-fw fab fa-telegram"></i> </a> <i class="fa-fw fas fa-link small" onclick="copyLink('', 'Link copied successfully!')" data-toggle="tooltip" data-placement="top" title="Copy link"> </i> </span></div></div></div></div></div><div id="panel-wrapper" class="col-xl-3 pl-2 text-muted topbar-down"><div class="access"><div id="access-lastmod" class="post"> <span>Recent Update</span><ul class="post-content pl-0 pb-1 ml-1 mt-2"><li><a href="/posts/polymorphism-inheritance/">객체지향에서의 상속과 다형성</a><li><a href="/posts/graduation-project-review/">졸업 작품 프로젝트 회고</a><li><a href="/posts/reflection-1/">[JAVA] Java Refelction 마스터 강의 1장</a><li><a href="/posts/mst/">[알고리즘] MST - 크루스칼 vs 프림</a><li><a href="/posts/injection/">[Spring] 의존성 주입 시 생성자 주입을 사용해야 하는 이유 </a></ul></div><div id="access-tags"> <span>Trending Tags</span><div class="d-flex flex-wrap mt-3 mb-1 mr-3"> <a class="post-tag" href="/tags/java/">java</a> <a class="post-tag" href="/tags/%EC%9E%90%EB%B0%94/">자바</a> <a class="post-tag" href="/tags/java-study/">java study</a> <a class="post-tag" href="/tags/%EC%9E%90%EB%B0%94-%EC%8A%A4%ED%84%B0%EB%94%94/">자바 스터디</a> <a class="post-tag" href="/tags/oop/">oop</a> <a class="post-tag" href="/tags/programming/">programming</a> <a class="post-tag" href="/tags/spring/">spring</a> <a class="post-tag" href="/tags/jpa/">jpa</a> <a class="post-tag" href="/tags/algorithm/">algorithm</a> <a class="post-tag" href="/tags/guides/">guides</a></div></div></div><script src="https://cdn.jsdelivr.net/gh/afeld/bootstrap-toc@1.0.1/dist/bootstrap-toc.min.js"></script><div id="toc-wrapper" class="pl-0 pr-4 mb-5"> <span class="pl-3 pt-2 mb-2">Contents</span><nav id="toc" data-toggle="toc"></nav></div></div></div><div class="row"><div class="col-12 col-lg-11 col-xl-8"><div id="post-extend-wrapper" class="pl-1 pr-1 pl-sm-2 pr-sm-2 pl-md-4 pr-md-4"><div id="related-posts" class="mt-5 mb-2 mb-sm-4"><h3 class="pt-2 mt-1 mb-4 ml-1" data-toc-skip>Further Reading</h3><div class="card-deck mb-4"><div class="card"> <a href="/posts/javastudy01/"><div class="card-body"> <span class="timeago small" >Aug 8, 2021<i class="unloaded">2021-08-08T00:00:00+09:00</i> </span><h3 class="pt-0 mt-1 mb-3" data-toc-skip>자바 스터디 01 - JVM이란</h3><div class="text-muted small"><p> 들어가면서 백기선님이 진행하신 자바 스터디 강의와 스터디에 참여하신 분들의 자료를 참고하여 작성한 글입니다. 강의 링크 : [자바 뉴스 라이브] 2020/11/14, 자바 스터디 1주차 깃허브 링크 : 1주차 과제: JVM은 무엇이며 자바 코드는 어떻게 실행하는 것인가. 목차 JVM이란 무엇인가 컴파일 하는 방법 실행하는 방법 바...</p></div></div></a></div><div class="card"> <a href="/posts/javastudy02/"><div class="card-body"> <span class="timeago small" >Aug 10, 2021<i class="unloaded">2021-08-10T00:00:00+09:00</i> </span><h3 class="pt-0 mt-1 mb-3" data-toc-skip>자바 스터디 02 - 자바 데이터 타입, 변수 그리고 배열</h3><div class="text-muted small"><p> 들어가면서 백기선님이 진행하신 자바 스터디 강의와 스터디에 참여하신 분들의 자료를 참고하여 작성한 글입니다. 강의 링크 : [자바 뉴스 라이브] 2020/11/21, 자바 스터디 2주차 깃허브 링크 : 2주차 과제: 자바 데이터 타입, 변수 그리고 배열 목차 프리미티브 타입 종류와 값의 범위 그리고 기본 값 프리미티브 타입과 레퍼런스 타...</p></div></div></a></div><div class="card"> <a href="/posts/javastudy03/"><div class="card-body"> <span class="timeago small" >Aug 11, 2021<i class="unloaded">2021-08-11T00:00:00+09:00</i> </span><h3 class="pt-0 mt-1 mb-3" data-toc-skip>자바 스터디 03 - 연산자</h3><div class="text-muted small"><p> 들어가면서 백기선님이 진행하신 자바 스터디 강의와 스터디에 참여하신 분들의 자료를 참고하여 작성한 글입니다. 강의 영상 링크 : [자바 라이브 스터디] 2020/11/28, 자바 스터디 3주차 연산자를 알아보자. 강의 깃허브 링크 : 3주차 과제: 연산자 목차 산술 연산자 비트 연산자 관계 연산자 논리 연산자 instance...</p></div></div></a></div></div></div><div class="post-navigation d-flex justify-content-between"> <a href="/posts/javastudy08/" class="btn btn-outline-primary" prompt="Older"><p>자바 스터디 08 - 인터페이스</p></a> <a href="/posts/javastudy10/" class="btn btn-outline-primary" prompt="Newer"><p>자바 스터디 10 - 멀티쓰레드 프로그래밍</p></a></div></div></div></div><footer class="d-flex w-100 justify-content-center"><div class="d-flex justify-content-between align-items-center"><div class="footer-left"><p class="mb-0"> © 2022 <a href="https://twitter.com/username">yeoji21</a>. <span data-toggle="tooltip" data-placement="top" title="Except where otherwise noted, the blog posts on this site are licensed under the Creative Commons Attribution 4.0 International (CC BY 4.0) License by the author.">Some rights reserved.</span></p></div><div class="footer-right"><p class="mb-0"> Powered by <a href="https://jekyllrb.com" target="_blank" rel="noopener">Jekyll</a> with <a href="https://github.com/cotes2020/jekyll-theme-chirpy" target="_blank" rel="noopener">Chirpy</a> theme.</p></div></div></footer></div><div id="search-result-wrapper" class="d-flex justify-content-center unloaded"><div class="col-12 col-sm-11 post-content"><div id="search-hints"><h4 class="text-muted mb-4">Trending Tags</h4><a class="post-tag" href="/tags/java/">java</a> <a class="post-tag" href="/tags/%EC%9E%90%EB%B0%94/">자바</a> <a class="post-tag" href="/tags/java-study/">java study</a> <a class="post-tag" href="/tags/%EC%9E%90%EB%B0%94-%EC%8A%A4%ED%84%B0%EB%94%94/">자바 스터디</a> <a class="post-tag" href="/tags/oop/">oop</a> <a class="post-tag" href="/tags/programming/">programming</a> <a class="post-tag" href="/tags/spring/">spring</a> <a class="post-tag" href="/tags/jpa/">jpa</a> <a class="post-tag" href="/tags/algorithm/">algorithm</a> <a class="post-tag" href="/tags/guides/">guides</a></div><div id="search-results" class="d-flex flex-wrap justify-content-center text-muted mt-3"></div></div></div></div><div id="mask"></div><a id="back-to-top" href="#" aria-label="back-to-top" class="btn btn-lg btn-box-shadow" role="button"> <i class="fas fa-angle-up"></i> </a> <script src="https://cdn.jsdelivr.net/npm/simple-jekyll-search@1.7.3/dest/simple-jekyll-search.min.js"></script> <script> SimpleJekyllSearch({ searchInput: document.getElementById('search-input'), resultsContainer: document.getElementById('search-results'), json: '/assets/js/data/search.json', searchResultTemplate: '<div class="pl-1 pr-1 pl-sm-2 pr-sm-2 pl-lg-4 pr-lg-4 pl-xl-0 pr-xl-0"> <a href="https://yeoji21.github.io{url}">{title}</a><div class="post-meta d-flex flex-column flex-sm-row text-muted mt-1 mb-1"> {categories} {tags}</div><p>{snippet}</p></div>', noResultsText: '<p class="mt-5">Oops! No result founds.</p>', templateMiddleware: function(prop, value, template) { if (prop === 'categories') { if (value === '') { return `${value}`; } else { return `<div class="mr-sm-4"><i class="far fa-folder fa-fw"></i>${value}</div>`; } } if (prop === 'tags') { if (value === '') { return `${value}`; } else { return `<div><i class="fa fa-tag fa-fw"></i>${value}</div>`; } } } }); </script> <script src="https://cdn.jsdelivr.net/combine/npm/lozad/dist/lozad.min.js,npm/magnific-popup@1/dist/jquery.magnific-popup.min.js"></script> <script defer src="/assets/js/dist/post.min.js"></script> <script src="https://cdn.jsdelivr.net/combine/npm/popper.js@1.16.1,npm/bootstrap@4/dist/js/bootstrap.min.js"></script> <script defer src="/app.js"></script> <script defer src="https://www.googletagmanager.com/gtag/js?id="></script> <script> document.addEventListener("DOMContentLoaded", function(event) { window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', ''); }); </script>
